### PR TITLE
Add axios peer dependency

### PR DESCRIPTION
**Pull request by Isigiel**
First of all, awesome project I'm very interested in this and think it's a major flaw on the side of contentful. If you need any help I would love to give a hand.

Secondly, it seems like you are referencing axios types in your service, which leads to a crash if it's not already installed in the project.

### CODE REVIEW

**Comment by patrickhousley** [comment]
Hmm, ok so looks like I had CircleCI misconfigured so I didn't get any notifications for the PR and no builds are happening..my bad. The reason I didn't put it as a peerDependency is because contentful actually uses their own forked copy of axios, wonderful right. So is this a problem in projects not using contentful or did you see this issue in a contentful project?

**Comment by Isigiel** [comment]
I saw the issue in a project that already depended on contentful. I guess
you could copy out those couple of types to avoid the dependency, it is
kinda stupid to install axios just for the types.
Also I opened prs on the contentful ask that will make your adapter usable
and tried it out already. Works like a charm.

**Comment by Isigiel** [comment]
Another idea would probably be to have the use pass in the types when using the service, also kinda dumb but maybe better than bundling axios or copying the types.
Otherwise maybe mention the axios thing in the README, probably in a contentful section.

**Comment by patrickhousley** [comment]
OK, so I tried my damnedest to break an example repo with this but I couldn't. Merging.

**Pull request merged**
